INSERT INTO ACTORS
WITH
	LAST_YEAR AS (
		SELECT
			*
		FROM
			ACTORS
		WHERE
			CURRENT_YEAR = 1969
	),
	THIS_YEAR AS (
		SELECT
			*
		FROM
			ACTOR_FILMS
		WHERE
			YEAR = 1970
	)
SELECT
	COALESCE(LY.ACTOR, TY.ACTOR),
	COALESCE(LY.FILMS, ARRAY[]::FILMS[]) || CASE
		WHEN TY.YEAR IS NOT NULL THEN ARRAY[
			ROW (TY.FILM, TY.VOTES, TY.RATING, TY.FILMID)::FILMS
		]
		ELSE ARRAY[]::FILMS[]
	END AS FILMS,
	CASE
		WHEN TY.FILM IS NOT NULL THEN (
			CASE
				WHEN (TY.RATING) > 8 THEN 'star'
				WHEN (TY.RATING) > 7 THEN 'good'
				WHEN (TY.RATING) > 6 THEN 'average'
				ELSE 'bad'
			END
		)
	END AS QUALITY_CLASS,
	TY.YEAR IS NOT NULL AS IS_ACTIVE,
	TY.YEAR AS CURRENT_YEAR
FROM
	LAST_YEAR LY
	FULL OUTER JOIN THIS_YEAR TY ON LY.ACTOR = TY.ACTOR
	