-- CREATE TABLE PLAYERS_SCD (
-- 	PLAYER_NAME TEXT,
-- 	SCORING_CLASS SCORING_CLASS,
-- 	IS_ACTIVE BOOLEAN,
-- 	START_SEASON INTEGER,
-- 	END_SEASON INTEGER,
-- 	CURRENT_SEASON INTEGER,
-- 	PRIMARY KEY (PLAYER_NAME, Start_season)
-- )
-- DROP TABLE PLAYERS_SCD
INSERT INTO PLAYERS_SCD
WITH
	WITH_PREVIOUS AS (
		SELECT
			PLAYER_NAME,
			CURRENT_SEASON,
			SCORING_CLASS,
			IS_ACTIVE,
			LAG(SCORING_CLASS, 1) OVER (
				PARTITION BY
					PLAYER_NAME
				ORDER BY
					CURRENT_SEASON
			) AS PREVIOUS_SCORING_CLASS,
			LAG(IS_ACTIVE, 1) OVER (
				PARTITION BY
					PLAYER_NAME
				ORDER BY
					CURRENT_SEASON
			) AS PREVIOUS_IS_ACTIVE
		FROM
			PLAYERS
			WHERE current_season<=2021
	),
	WITH_INDICATORS AS (
		SELECT
			*,
			CASE
				WHEN SCORING_CLASS <> PREVIOUS_SCORING_CLASS THEN 1
				WHEN IS_ACTIVE <> PREVIOUS_IS_ACTIVE THEN 1
				ELSE 0
			END AS CHANGE_INDICATOR
		FROM
			WITH_PREVIOUS
	),
	WITH_STREAK AS (
		SELECT
			*,
			SUM(CHANGE_INDICATOR) OVER (
				PARTITION BY
					PLAYER_NAME
				ORDER BY
					CURRENT_SEASON
			) AS STREAK_IDENTIFIER
		FROM
			WITH_INDICATORS
	)
SELECT
	PLAYER_NAME,
		SCORING_CLASS,
	IS_ACTIVE,

	MIN(CURRENT_SEASON) AS START_SEASON,
	MAX(CURRENT_SEASON) AS END_SEASON,
	2021 AS Current_season
FROM
	WITH_STREAK
GROUP BY
	PLAYER_NAME,
	STREAK_IDENTIFIER,
	IS_ACTIVE,
	SCORING_CLASS
ORDER BY
	PLAYER_NAME


	SELECT* FROM Players_scd