WITH
	AGG AS (
		SELECT
			METRIC_NAME,
			MONTH_START,
			ARRAY[
				SUM(METRIC_ARRAY[1]),
				SUM(METRIC_ARRAY[2]),
				SUM(METRIC_ARRAY[3])
			] AS SUMMED_ARRAY
		FROM
			ARRAY_METRICS
		GROUP BY
			METRIC_NAME,
			MONTH_START
	)
	-- Select and display the metric_name, date (adjusted by index), and summed value
SELECT
	METRIC_NAME,
	MONTH_START + CAST(CAST(INDEX - 1 AS TEXT) || ' day' AS INTERVAL) AS ADJUSTED_DATE,
	ELEM AS VALUE
FROM
	AGG
	CROSS JOIN UNNEST(AGG.SUMMED_ARRAY) WITH ORDINALITY AS A (ELEM, INDEX);