-- CREATE TYPE SCD_TYPE AS (
-- 	SCORING_CLASS SCORING_CLASS,
-- 	IS_ACTIVE BOOLEAN,
-- 	START_SEASON INTEGER,
-- 	END_SEASON INTEGER
-- )
WITH
	LAST_SEASON_DATA AS (
		SELECT
			*
		FROM
			PLAYERS_SCD
		WHERE
			CURRENT_SEASON = 2021
	),
	HISTORICAL_SCD AS (
		SELECT
			PLAYER_NAME,
			SCORING_CLASS,
			IS_ACTIVE,
			START_SEASON,
			END_SEASON
		FROM
			PLAYERS_SCD
		WHERE
			CURRENT_SEASON = 2021
			AND CURRENT_SEASON < 2021
	),
	THIS_SEASON_DATA AS (
		SELECT
			*
		FROM
			PLAYERS
		WHERE
			CURRENT_SEASON = 2022
	),
	UNCHANGED_RECORDS AS (
		SELECT
			TS.PLAYER_NAME,
			TS.SCORING_CLASS,
			TS.IS_ACTIVE,
			LS.START_SEASON,
			LS.CURRENT_SEASON AS END_DATE
		FROM
			THIS_SEASON_DATA TS
			LEFT JOIN LAST_SEASON_DATA LS ON LS.PLAYER_NAME = TS.PLAYER_NAME
		WHERE
			TS.SCORING_CLASS = LS.SCORING_CLASS
			AND TS.IS_ACTIVE = LS.IS_ACTIVE
	),
	CHANGED_RECORDS AS (
		SELECT
			TS.PLAYER_NAME,
			UNNEST(
				ARRAY[
					ROW (
						LS.SCORING_CLASS,
						LS.IS_ACTIVE,
						LS.START_SEASON,
						LS.END_SEASON
					)::SCD_TYPE,
					ROW (
						TS.SCORING_CLASS,
						TS.IS_ACTIVE,
						TS.CURRENT_SEASON,
						TS.CURRENT_SEASON
					)::SCD_TYPE
				]
			) AS RECORDS
		FROM
			THIS_SEASON_DATA TS
			LEFT JOIN LAST_SEASON_DATA LS ON LS.PLAYER_NAME = TS.PLAYER_NAME
		WHERE
			TS.SCORING_CLASS <> LS.SCORING_CLASS
			OR TS.IS_ACTIVE <> LS.IS_ACTIVE
	),
	UNNESTED_CHANGED_RECORDS AS (
		SELECT
			PLAYER_NAME,
			(RECORDS::SCD_TYPE).SCORING_CLASS,
			(RECORDS::SCD_TYPE).IS_ACTIVE,
			(RECORDS::SCD_TYPE).START_SEASON,
			(RECORDS::SCD_TYPE).END_SEASON
		FROM
			CHANGED_RECORDS
	),
	NEW_RECORDS AS (
		SELECT
			TS.PLAYER_NAME,
			TS.SCORING_CLASS,
			TS.IS_ACTIVE,
			TS.CURRENT_SEASON AS START_SEASON,
			TS.CURRENT_SEASON AS END_SEASON
		FROM
			THIS_SEASON_DATA TS
			LEFT JOIN LAST_SEASON_DATA LS ON TS.PLAYER_NAME = LS.PLAYER_NAME
		WHERE
			LS.PLAYER_NAME IS NULL
	)
SELECT
	*
FROM
	HISTORICAL_SCD
UNION ALL
SELECT
	*
FROM
	UNCHANGED_RECORDS
UNION ALL
SELECT
	*
FROM
	UNNESTED_CHANGED_RECORDS
UNION ALL
SELECT
	*
FROM
	NEW_RECORDS